# dummy no-op config file
version: 2.1
jobs:
  build:
    docker:
      - image: busybox
    steps:
      - run: echo dummy
workflows:
  dummy:
    jobs:
      - build:
          filters:
            branches:
              only: /^$/
